from typing import List, Optional, Dict, Any
from src.config.settings import Config
from src.clients.github_client import GitHubClient
from src.utils.logger import get_logger
from datetime import datetime
import requests # Import requests to catch HTTPError

logger = get_logger(__name__)

class TestRepoClient:
    """Client for interacting with the Test Repository, including push/PR operations"""
    
    def __init__(self, config: Config, repo_url: str):
        self.config = config
        self.repo_url = repo_url
        # We reuse GitHubClient logic but need to point it to the test repo
        self.client = GitHubClient(config)
        self._override_repo_details(repo_url)
        
    def _override_repo_details(self, repo_url: str):
        """Override the repo details in the underlying client"""
        try:
            # Logic to parse owner/repo from URL
            # Expected format: owner/repo
            if "github.com/" in repo_url:
                parts = repo_url.split("github.com/")[-1].replace(".git", "").split("/")
                self.client.owner = parts[0]
                self.client.repo = parts[1]
            elif "/" in repo_url:
                parts = repo_url.split("/")
                self.client.owner = parts[0]
                self.client.repo = parts[1]
            logger.info(f"TestRepoClient configured for {self.client.owner}/{self.client.repo}")
        except Exception as e:
            logger.error(f"Failed to parse test repo URL {repo_url}: {e}")

    def list_test_files(self, path: str = "tests") -> List[str]:
        """List all test files in the repo"""
        try:
            # Using GitHubClient's tree fetch (assuming 'main' branch for listing existing files)
            files_dict = self.client.get_all_files_in_branch("main") 
            return list(files_dict.keys())
        except Exception as e:
            logger.error(f"Error listing test files: {e}")
            return []

    def get_file_content(self, path: str) -> Optional[str]:
        return self.client.get_cached_file_content("main", path)

    def push_tests_and_create_pr(
        self, 
        files_to_commit: Dict[str, str], 
        jira_ticket_key: str, 
        base_branch: str = "main"
    ) -> Dict[str, Any]:
        """
        Orchestrates commit and PR creation/update logic.
        
        If an open PR exists, it commits the new files to the existing PR's branch
        and updates the PR description.
        """
        if not files_to_commit:
            logger.warning("No files to commit. Skipping commit and PR.")
            return {"pr_url": "", "new_branch_name": "", "message": "No files to commit"}

        # --- MODIFIED: Define the fixed branch name ---
        new_branch = f"features/{jira_ticket_key.lower()}"
        
        commit_message = f"feat({jira_ticket_key}): Auto-generated E2E tests ({len(files_to_commit)} files)"
        pr_title = f"{jira_ticket_key}: E2E Tests Generated by QE Agent"
        
        # --- 1. Check for Existing PR ---
        # The client will look for this exact branch name or PR title prefix
        existing_pr = self.client.find_open_pr_by_jira_key(jira_ticket_key, base_branch)
        
        if existing_pr:
            # Case A: PR Exists - Update Commit and Body
            existing_head_ref = existing_pr['head_ref']
            logger.info(f"Existing PR found (#{existing_pr['number']}). Committing to branch: {existing_head_ref}")
            
            try:
                # 1. Push files to the existing branch
                self.client.push_files_to_branch(base_branch, existing_head_ref, files_to_commit, commit_message)
                
                # 2. Generate updated PR body
                pr_body = self._generate_pr_body(jira_ticket_key, existing_head_ref, files_to_commit, is_update=True)
                self.client.update_pr_body(existing_pr['number'], pr_body)
                
                return {
                    "pr_url": existing_pr['html_url'],
                    "new_branch_name": existing_head_ref,
                    "pr_number": existing_pr['number'],
                    "message": f"Successfully updated existing PR #{existing_pr['number']} with new commit."
                }
            except Exception as e:
                # Catch error if commit fails (e.g., conflicts, branch deleted, permission)
                logger.error(f"Failed to commit to existing PR branch {existing_head_ref}: {e}")
                raise Exception(f"GitHub Write/PR update failed: {str(e)}")

        else:
            # Case B: No PR Exists - Create New Branch and PR
            logger.info(f"No existing PR found. Creating new branch: {new_branch}")

            try:
                # 1. Create a new branch (This must be the full fixed branch name)
                self.client.create_branch(new_branch, base_branch)

                # 2. Push files (create blobs, tree, commit, and update ref)
                self.client.push_files_to_branch(base_branch, new_branch, files_to_commit, commit_message)
                
                # 3. Create the Pull Request
                pr_body = self._generate_pr_body(jira_ticket_key, new_branch, files_to_commit, is_update=False)
                pr_details = self.client.create_pull_request(new_branch, base_branch, pr_title, pr_body)
                
                return {
                    "pr_url": pr_details['pr_url'],
                    "new_branch_name": new_branch,
                    "pr_number": pr_details['pr_number'],
                    "message": f"Successfully committed {len(files_to_commit)} files and created PR {pr_details['pr_number']}"
                }

            except Exception as e:
                logger.error(f"Failed to push and create PR: {e}")
                raise Exception(f"GitHub Write/PR operation failed: {str(e)}")

    def _generate_pr_body(self, jira_ticket_key: str, branch: str, files_to_commit: Dict[str, str], is_update: bool) -> str:
        """Helper to generate the Markdown body for the PR."""
        action = "updated" if is_update else "generated"
        
        return f"""
        **QE Agent Automation Run ({'UPDATE' if is_update else 'NEW RUN'})**

        This Pull Request contains **{len(files_to_commit)}** auto-{action} Playwright E2E test files 
        for Jira ticket {jira_ticket_key}.

        **Summary of changes:**
        - **Branch:** `{branch}`
        - **Files {action.upper()}:** {', '.join(files_to_commit.keys())}
        - **Time of Action:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

        Please review and merge these changes to integrate the new test coverage.
        """