from typing import List, Optional, Dict, Any
from src.config.settings import Config
from src.clients.github_client import GitHubClient
from src.utils.logger import get_logger
from datetime import datetime

logger = get_logger(__name__)

class TestRepoClient:
    """Client for interacting with the Test Repository, including push/PR operations"""
    
    def __init__(self, config: Config, repo_url: str):
        self.config = config
        self.repo_url = repo_url
        # We reuse GitHubClient logic but need to point it to the test repo
        self.client = GitHubClient(config)
        self._override_repo_details(repo_url)
        
    def _override_repo_details(self, repo_url: str):
        """Override the repo details in the underlying client"""
        try:
            # Logic to parse owner/repo from URL
            # Expected format: owner/repo
            if "github.com/" in repo_url:
                parts = repo_url.split("github.com/")[-1].replace(".git", "").split("/")
                self.client.owner = parts[0]
                self.client.repo = parts[1]
            elif "/" in repo_url:
                parts = repo_url.split("/")
                self.client.owner = parts[0]
                self.client.repo = parts[1]
            logger.info(f"TestRepoClient configured for {self.client.owner}/{self.client.repo}")
        except Exception as e:
            logger.error(f"Failed to parse test repo URL {repo_url}: {e}")

    def list_test_files(self, path: str = "tests") -> List[str]:
        """List all test files in the repo"""
        try:
            # Using GitHubClient's tree fetch (assuming 'main' branch for listing existing files)
            files_dict = self.client.get_all_files_in_branch("main") 
            return list(files_dict.keys())
        except Exception as e:
            logger.error(f"Error listing test files: {e}")
            return []

    def get_file_content(self, path: str) -> Optional[str]:
        return self.client.get_cached_file_content("main", path)

    def push_tests_and_create_pr(
        self, 
        files_to_commit: Dict[str, str], 
        jira_ticket_key: str, 
        base_branch: str = "main"
    ) -> Dict[str, Any]:
        """
        High-level orchestration to push test files and create a Pull Request.
        
        Args:
            files_to_commit: Dictionary of {file_path: file_content}
            jira_ticket_key: Jira ticket key (e.g., PROJ-123)
            base_branch: The target branch for the PR (default: main)

        Returns:
            Dictionary with pr_url and new_branch_name.
        """
        if not files_to_commit:
            logger.warning("No files to commit. Skipping branch creation and PR.")
            return {"pr_url": "", "new_branch_name": "", "message": "No files to commit"}

        # --- MODIFIED: Branch name starts with 'tests/' ---
        new_branch = f"tests/{jira_ticket_key.lower()}-{datetime.now().strftime('%Y%m%d%H%M%S')}"
        
        commit_message = f"feat({jira_ticket_key}): Auto-generated E2E tests"
        pr_title = f"{jira_ticket_key}: E2E Tests Generated by QE Agent"
        pr_body = f"""
        **QE Agent Automation Run**

        This Pull Request contains **{len(files_to_commit)}** auto-generated Playwright E2E test files 
        for Jira ticket {jira_ticket_key}.

        **Summary of changes:**
        - **Branch:** `{new_branch}`
        - **Generated Files:** {', '.join(files_to_commit.keys())}

        Please review and merge these changes to integrate the new test coverage.
        """
        
        try:
            # 1. Create a new branch
            self.client.create_branch(new_branch, base_branch)
            logger.info(f"Branch '{new_branch}' created successfully.")

            # 2. Push files (create blobs, tree, commit, and update ref)
            self.client.push_files_to_branch(base_branch, new_branch, files_to_commit, commit_message)
            logger.info(f"Files committed successfully to '{new_branch}'.")

            # 3. Create the Pull Request
            pr_details = self.client.create_pull_request(new_branch, base_branch, pr_title, pr_body)
            
            return {
                "pr_url": pr_details['pr_url'],
                "new_branch_name": new_branch,
                "pr_number": pr_details['pr_number'],
                "message": f"Successfully committed {len(files_to_commit)} files and created PR {pr_details['pr_number']}"
            }

        except Exception as e:
            logger.error(f"Failed to push and create PR: {e}")
            raise Exception(f"GitHub Write/PR operation failed: {str(e)}")